
parameters:
  class.guzzle.client: GuzzleHttp\Client
  class.guzzle.emitter: GuzzleHttp\Event\Emitter
  class.guzzle.oauthplugin: GuzzleHttp\Subscriber\Oauth\Oauth1
 
services:
  guzzle.twitter.emitter:
      class: %class.guzzle.emitter%
      calls:
          - [attach, [@guzzle.twitter.oauthplugin]]

  guzzle.twitter.client:
      class: %class.guzzle.client%
      arguments:
          - {base_url: [%twitter.base_url%, {version: %twitter.version%}], defaults: {auth: 'oauth'}, emitter: @guzzle.twitter.emitter}

  guzzle.twitter.oauthplugin:
      class: %class.guzzle.oauthplugin%
      arguments: [%twitter.config%]
        
  twitter.repository:
    class: Infrastructure\GuzzleTwitterRepository
    arguments: ["@guzzle.twitter.client"]
    
  twitter_service:
    class: Application\TwitterService
    arguments: ["@twitter.repository"]